name: simple_ecommerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: 5.4.0
  flutter_staggered_grid_view: 0.7.0
  intl: 0.19.0
  cached_network_image: 3.3.0
  flutter: 
    sdk: flutter
  flutter_native_splash : any

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  

flutter_native_splash:
  android: true
  background_image: assets/bg.jpg
  image: assets/flutter_logo.png

  
  color: "#02a895"

flutter: 
  uses-material-design: true

